include:
  # dyad

  - board: seeeduino_xiao_ble
    shield: dyad_central_left
  - board: seeeduino_xiao_ble
    shield: dyad_peripheral_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
